---
- name: set debconf main_mailer_type
  debconf:
    name: postfix
    question: postfix/main_mailer_type
    vtype: string
    value: "{{ postfix_debconf_mailer_type }}"

- name: check that postfix_mailname is set
  when: postfix_mailname == ''
  fail:
    msg: Please define the variable postfix_mailname!
  
- name: set debconf mailname
  debconf:
    name: postfix
    question: postfix/mailname
    vtype: string
    value: "{{ postfix_mailname }}"

- name: install helpers
  when: postfix_helpers_enabled
  apt:
    pkg: mailutils
    state: present
  tags:
    - helper

- name: install postfix packages
  apt:
    pkg: ['postfix', 'libsasl2-modules']
    state: present
