- name: create docker0.target
  copy:
    dest: "/etc/systemd/system/docker0.target"
    content: |
      [Unit]
      Description=target is active if docker network interface is available
      Requires=sys-subsystem-net-devices-docker0.device
      After=sys-subsystem-net-devices-docker0.device
  - notify: daemon-reload & restart postfix 

- name: create postfix@- override
  file:
    path: "/etc/systemd/system/postfix@-.service.d"
    state: directory
  copy:
    dest: "/etc/systemd/system/postfix@-.service.d/override.conf"
    content: |
      [Unit]
      After=docker0.target
      Requires=docker0.target
  - notify: daemon-reload & restart postfix 
