import os

import testinfra.utils.ansible_runner

testinfra_hosts = testinfra.utils.ansible_runner.AnsibleRunner(
    os.environ['MOLECULE_INVENTORY_FILE']).get_hosts('all')

SASL_PASSWORDS = """#
# Ansible managed: Do NOT edit this file manually!
#

## Per-sender authentication
#
# user1@example.com              username:password
#
# Login information for the default relayhost
# [mail.isp.example]             username:password
#
# Alternative form:
# [mail.isp.example]:submission  username:password
#
# Or:
# senderadress                   relayhost-login:password

server@example.com ServerExampleCom:verylongpassword"""


def test_sasl_passwords(host):
    f = host.file('/etc/postfix/sasl-passwords')
    db = host.file('/etc/postfix/sasl-passwords.db')

    assert f.exists
    assert db.exists

    assert f.content_string == SASL_PASSWORDS
