import os

import testinfra.utils.ansible_runner

testinfra_hosts = testinfra.utils.ansible_runner.AnsibleRunner(
    os.environ['MOLECULE_INVENTORY_FILE']).get_hosts('all')

SENDER_CANONICAL_MAPS = """#
# Ansible managed: Do NOT edit this file manually!
#

root server@example.com
root@{hostname} server@example.com
root@{hostname} server@example.com"""


def test_sender_canonical_maps(host):
    f = host.file('/etc/postfix/sender-canonical-maps')
    db = host.file('/etc/postfix/sender-canonical-maps.db')

    assert f.exists
    assert db.exists

    assert f.content_string == SENDER_CANONICAL_MAPS.format(hostname=host.run('hostname -s').stdout)
