---
- name: postmap postfix
  command: "postmap {{ postfix_tpl_item }}"
  with_items:
    - '/etc/postfix/sasl-passwords'
    - '/etc/postfix/sender-canonical-maps-regex'
  loop_control:
    loop_var: postfix_tpl_item
  notify:
    - newaliases

- name: newaliases
  command: newaliases

- name: reload postfix
  service:
    name: postfix
    state: restarted
