---
- name: template /etc/mailname
  lineinfile:
    line: "{{ inventory_hostname }}"
    path: /etc/mailname
    owner: root
    group: root
    mode: 0644
  notify:
    - reload postfix

- name: template /etc/postfix/main.cf
  template:
    src: "etc/postfix/main.cf.j2"
    dest: "/etc/postfix/main.cf"
  notify:
    - reload postfix

- name: template the postmap files
  template:
    src: "{{ postfix_postmap_tpl_item }}.j2"
    dest: "/{{ postfix_postmap_tpl_item }}"
    owner: root
    group: root
    mode: 0640
  with_items:
    - etc/postfix/relayhost-maps
    - etc/postfix/sasl-passwords
    - etc/postfix/sender-canonical-maps
    - etc/postfix/sender-canonical-maps-regex
  loop_control:
    loop_var: postfix_postmap_tpl_item
  notify:
    - postmap postfix

- name: template the /etc/aliases file
  lineinfile:
    path: /etc/aliases
    regexp: '^{{ alias_item.name }}: '
    line: '{{ alias_item.name }}: {{ alias_item.target }}'
  with_items: '{{ postfix_aliases }}'
  loop_control:
    loop_var: alias_item
  notify: newaliases
