import os

import testinfra.utils.ansible_runner

testinfra_hosts = testinfra.utils.ansible_runner.AnsibleRunner(
    os.environ['MOLECULE_INVENTORY_FILE']).get_hosts('all')

SENDER_CANONICAL_MAPS_REGEX = """#
# Ansible managed: Do NOT edit this file manually!
#

/^(.*@){hostname}$/     server@example.com
/^(.*@){hostname}$/           server@example.com"""


def test_sender_canonical_maps_regex(host):
    f = host.file('/etc/postfix/sender-canonical-maps-regex')

    assert f.exists
    assert f.content_string == SENDER_CANONICAL_MAPS_REGEX.format(hostname=host.run('hostname -s').stdout)
